### ISSUE TITLE
Published on Maven Central

### ISSUE THREAD

**Issue by j-roskopf** [Kotlin/Storytale#13]
Is this plugin published to Maven Central as it states in the readme? I tried searching on Maven Central and I couldn't find it. 

Thanks!

**Comment by PMARZV** [comment]
I dont think so
<details><summary>Stack Trace when trying to import plugin</summary>
<p>
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.jetbrains.compose.storytale', version: '1.0', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (No included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.compose.storytale:org.jetbrains.compose.storytale.gradle.plugin:1.0')
  Searched in the following repositories:
    MavenLocal(file:/C:/Users/Pau%20Marzo/.m2/repository/)
    Google
    MavenRepo
    Gradle Central Plugin Repository
    maven(https://maven.pkg.jetbrains.space/public/p/compose/dev)
    maven2(https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev/)
	at org.gradle.plugin.use.resolve.internal.PluginResolutionResult.getFound(PluginResolutionResult.java:112)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolvePluginRequest(DefaultPluginRequestApplicator.java:192)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:97)
	at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:45)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:212)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:385)


</p>
</details>

**Comment by whitescent** [comment]
Sorry, I forgot to update its status in the README. It hasn't actually been released to Maven Central yet, and a lot of things are still a work in progress. I'll update the README later 🙏

**Comment by j-roskopf** [comment]
no worries at all! the plugin looked super interested and I was excited to try it out :)

**Comment by sindrenm** [comment]
Fixed by https://github.com/Kotlin/Storytale/pull/14?

**Comment by whitescent** [comment]
#14 Corrected the status of this project on maven Central, this issue will be closed when we release the first version 😃

**Comment by JSMonk** [comment]
So, we've just published our first public dev build, so, I think the issue could be close.
To use it in your project, please follow the following steps described here: https://github.com/Kotlin/Storytale?tab=readme-ov-file#1-setup
