### ISSUE TITLE
Unable to load class 'org.jetbrains.kotlin.gradle.plugin.mpp.PublishingKt'

### ISSUE THREAD

**Issue by mirzemehdi** [Kotlin/Storytale#31]
This happens with kotlin version is `2.1.0`. 

Workaround:
downgrading kotlin version to `2.0.21`

**Comment by CRamsan** [comment]
Any plans for adding compatibility with newer versions of Kotlin?

**Comment by JSMonk** [comment]
@CRamsan sure. I'm going to fix it soon and publish it on Monday. 
I'm so sorry for the delay and such an issue.

**Comment by CRamsan** [comment]
Let me know if I can help with anything. Thanks for your work!

**Comment by JSMonk** [comment]
@CRamsan @mirzemehdi, We've published the `0.0.2+dev6` version, which works with 2.1.0. Could you please check if the issue is reproducible on your side (I checked it on our `exmaple` project, and it worked for me)

**Comment by CRamsan** [comment]
Thanks for the update! I am fairly new to this project so may have missed some configurations or documentations. I gave it a try and here are some things I found:

- The gradle module now syncs and I was able to run it on the JVM target.
- For each submodule, I am getting this warning: `> Configure project :ui-catalog
w: The artifact `org.jetbrains.kotlin:kotlin-compiler-embeddable` is present in the build classpath along Kotlin Gradle plugin.
This may lead to unpredictable and inconsistent behavior.
For more details, see: https://kotl.in/gradle/internal-compiler-symbols
`
It is only a warning but the project is able to compile and run*.

I am also getting the following errors, but they do not repro in the example project. So my assumption is that there may be other configurations in my project that are causing them. I will leave them here for reference just in case:
- On the wasm target when I run `wasmJsBrowserStoriesDevelopmentRun` the page does not render. The issue seems to be the MIME type of the javascript file. This is the error:
`Refused to execute script from 'http://localhost:8080/composeApp.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.` 
![Image](https://github.com/user-attachments/assets/c3c5d14b-f8d9-494a-83c6-1995b124c516)
- When I run `jvmStoriesRun` the catalog window appears but when I click on a story I get this error: 
`Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'void com.cramsan.ui.components.DropdownKt.Dropdown(java.lang.String, androidx.compose.ui.Modifier, java.util.List, java.util.List, kotlin.jvm.functions.Function1, kotlin.jvm.functions.Function1, androidx.compose.runtime.Composer, int)'
	at com.cramsan.ui.components.DropdownKt$special$$inlined$story$1.invoke(StoryDelegate.kt:38)
	at com.cramsan.ui.components.DropdownKt$special$$inlined$story$1.invoke(StoryDelegate.kt:12)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at org.jetbrains.compose.storytale.gallery.platform.StoryGallery_desktopKt$GalleryContent$1$1$1$1.invoke(StoryGallery.desktop.kt:123)`

As I said, the example project in this repo works fine with your changes. Thanks for all the help!

**Comment by nathanfallet** [comment]
Had the same issue today with `0.0.1+dev5` and Kotlin `2.1.10`, seems we cannot upgrade to the new version:

```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.jetbrains.compose.storytale:compiler-plugin:0.0.2+dev6.
```
